name: action

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  action:
    strategy:
      matrix:
        runs-on:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: check styles
        run: deno fmt --check

      - name: check types
        run: deno check $(deno eval 'console.log(...(await import("https://esm.sh/glob")).sync("**/*.ts"))')

      - name: test codes
        run: deno test --allow-read --allow-write
